---
language: ruby
cache: bundler

dist: trusty
sudo: false

notifications:
  email: false

rvm:
  - 2.5

addons:
  postgresql: '9.6'

env:
  global:
    - METKA_DB_USER=postgres
    - METKA_DB_NAME=metka

before_install:
  - gem install -v 2.0.2 bundler

before_script:
  - gem update --system
  - RAILS_ENV=test bundle exec rake dummy:db:create dummy:db:schema:load
