---
language: ruby
cache: bundler

dist: trusty
sudo: false

notifications:
  email: false

services:
  - postgresql
addons:
  postgresql: "11.2"

before_install:
  - gem install -v 2.1.4 bundler
  - sudo apt-get update
  - sudo apt-get --yes remove postgresql\*
  - sudo apt-get install -y postgresql-11 postgresql-client-11
  - sudo cp /etc/postgresql/{9.6,11}/main/pg_hba.conf
  - sudo service postgresql restart 11

before_script:
  - psql -c 'CREATE ROLE travis SUPERUSER LOGIN CREATEDB;' -U postgres
  - ./bin/setup

matrix:
  include:
    - rvm: 2.5.8
      gemfile: gemfiles/rails52.gemfile
    - rvm: 2.6.6
      gemfile: gemfiles/rails6.gemfile
    - rvm: 2.7.2
      gemfile: gemfiles/rails61.gemfile
    - rvm: 3.0.0
      gemfile: gemfiles/rails61.gemfile
