---
language: ruby
cache: bundler

dist: trusty
sudo: false

notifications:
  email: false

addons:
  postgresql: '9.6'

env:
  global:
    - METKA_DB_USER=postgres
    - METKA_DB_NAME=metka

before_install:
  - gem install -v 2.0.2 bundler

before_script:
  - gem update --system
  - RAILS_ENV=test bundle exec rake dummy:db:create dummy:db:schema:load

matrix:
  include:
    - rvm: 2.5.1
      gemfile: gemfiles/rails5.gemfile
    - rvm: 2.5.5
      gemfile: gemfiles/rails52.gemfile
    - rvm: 2.6.2
      gemfile: gemfiles/rails6.gemfile
