# frozen_string_literal: true

# The SQLite index strategy for the posts table, as generated by
# `rails g metka:strategies:index --source-table-name=posts
# --source-columns=tags categories`. PostgreSQL needs no index strategy —
# the GIN indexes already serve tag queries — so this is a no-op there.
class CreatePostsIndexTables < ActiveRecord::Migration[5.0]
  COLUMNS = %w[tags categories].freeze

  def up
    return unless connection.adapter_name.match?(/sqlite/i)

    COLUMNS.each do |column|
      execute <<-SQL
      CREATE TABLE posts_#{column}_index (
        tag_name varchar NOT NULL,
        record_id bigint NOT NULL,
        PRIMARY KEY (tag_name, record_id)
      ) WITHOUT ROWID;
      SQL

      execute <<-SQL
      INSERT OR IGNORE INTO posts_#{column}_index (tag_name, record_id)
        SELECT value, posts.id FROM posts, json_each(posts.#{column});
      SQL

      execute <<-SQL
      CREATE TRIGGER metka_idx_ins_on_posts_#{column}
      AFTER INSERT ON posts
      FOR EACH ROW
      BEGIN
        INSERT OR IGNORE INTO posts_#{column}_index (tag_name, record_id)
        SELECT value, NEW.id FROM json_each(NEW.#{column});
      END;
      SQL

      execute <<-SQL
      CREATE TRIGGER metka_idx_upd_on_posts_#{column}
      AFTER UPDATE OF #{column} ON posts
      FOR EACH ROW
      BEGIN
        DELETE FROM posts_#{column}_index
        WHERE tag_name IN (SELECT value FROM json_each(OLD.#{column}))
          AND record_id = OLD.id;

        INSERT OR IGNORE INTO posts_#{column}_index (tag_name, record_id)
        SELECT value, NEW.id FROM json_each(NEW.#{column});
      END;
      SQL

      execute <<-SQL
      CREATE TRIGGER metka_idx_del_on_posts_#{column}
      AFTER DELETE ON posts
      FOR EACH ROW
      BEGIN
        DELETE FROM posts_#{column}_index
        WHERE tag_name IN (SELECT value FROM json_each(OLD.#{column}))
          AND record_id = OLD.id;
      END;
      SQL
    end
  end

  def down
    return unless connection.adapter_name.match?(/sqlite/i)

    COLUMNS.each do |column|
      execute "DROP TRIGGER IF EXISTS metka_idx_ins_on_posts_#{column};"
      execute "DROP TRIGGER IF EXISTS metka_idx_upd_on_posts_#{column};"
      execute "DROP TRIGGER IF EXISTS metka_idx_del_on_posts_#{column};"
      execute "DROP TABLE IF EXISTS posts_#{column}_index;"
    end
  end
end
