name: Release

on:
  release:
    types: [published]

permissions:
  contents: read

jobs:
  push:
    runs-on: ubuntu-latest
    environment: rubygems
    permissions:
      contents: read
      id-token: write
    steps:
    - uses: actions/checkout@fbc6f3992d24b796d5a048ff273f7fcc4a7b6c09 # v5.1.0
    - uses: ruby/setup-ruby@95ef2b042f9d7a56d8268cba8559e2842e2ad01b # v1.321.0
      with:
        ruby-version: "3.4"
        bundler-cache: true
    - uses: rubygems/release-gem@7f9650160c1a4e7989fdc9855807bdbd421d8b6b # v1.4.1
