name: Release

on:
  release:
    types: [published]

permissions:
  contents: read

jobs:
  push:
    runs-on: ubuntu-latest
    environment: rubygems
    permissions:
      contents: read
      id-token: write
    steps:
    - uses: actions/checkout@fbc6f3992d24b796d5a048ff273f7fcc4a7b6c09 # v5.1.0
    - uses: ruby/setup-ruby@e5517072e87f198d9533967ae13d97c11b604005 # v1.99.0
      with:
        ruby-version: "3.4"
        bundler-cache: true
    - uses: rubygems/release-gem@7f9650160c1a4e7989fdc9855807bdbd421d8b6b # v1.4.1
