name: Specs

on:
  push:
    branches:
    - master
  pull_request:
  schedule:
    - cron: "0 3 * * 1" # Every monday at 3 AM

permissions:
  contents: read

jobs:
  rspec:
    runs-on: ubuntu-latest
    name: Ruby ${{ matrix.ruby }} / ${{ matrix.gemfile }} / PostgreSQL ${{ matrix.postgres }}
    continue-on-error: ${{ matrix.allow-failure || false }}
    env:
      BUNDLE_GEMFILE: ${{ matrix.gemfile }}
      BUNDLE_JOBS: 4
      BUNDLE_RETRY: 3
      CI: true
      RAILS_ENV: test
      DATABASE_URL: postgres://postgres:postgres@localhost:5432
    strategy:
      fail-fast: false
      matrix:
        include:
        - ruby: "3.4"
          postgres: "18"
          gemfile: "gemfiles/rails81.gemfile"
        - ruby: "3.4"
          postgres: "17"
          gemfile: "gemfiles/rails80.gemfile"
        - ruby: "3.3"
          postgres: "17"
          gemfile: "gemfiles/rails72.gemfile"
        - ruby: "3.2"
          postgres: "16"
          gemfile: "gemfiles/rails71.gemfile"
        - ruby: "3.4"
          postgres: "18"
          gemfile: "gemfiles/railsmain.gemfile"
          allow-failure: true
    services:
      postgres:
        image: postgres:${{ matrix.postgres }}
        ports: ["5432:5432"]
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
    - uses: actions/checkout@v5
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true
    - name: Prepare test database
      run: |
        bundle exec rake dummy:db:create
        bundle exec rake dummy:db:migrate:reset
    - name: Run RSpec
      run: bundle exec rspec -f d --force-color
